import type {CapabilityDefinition} from './types.js';
export const CAPABILITIES: CapabilityDefinition[] = [
 {capability_id:'observe.ai_answer',family:'observation',version:'1.0.0',request_schema_ref:'opengeo-job.v1.schema.json',result_schema_ref:'opengeo-observation.v1.schema.json',execution:{public_model:'job',turnaround_classes:['best_effort','expedited','interactive'],supports_partial_results:true,supports_cancel:true,supports_prefer_wait:true},billing:{unit:'observation',quoteable:true}},
 {capability_id:'generate.text',family:'generation',version:'1.0.0',request_schema_ref:'opengeo-job.v1.schema.json',result_schema_ref:'opengeo-publication.v1.schema.json',execution:{public_model:'job',turnaround_classes:['best_effort','interactive'],supports_partial_results:false,supports_cancel:true,supports_prefer_wait:true},billing:{unit:'content_asset',quoteable:true}},
 {capability_id:'publish.owned_site',family:'distribution',version:'1.0.0',request_schema_ref:'opengeo-publication.v1.schema.json',result_schema_ref:'opengeo-publication.v1.schema.json',execution:{public_model:'job',turnaround_classes:['best_effort','interactive'],supports_partial_results:false,supports_cancel:true,supports_prefer_wait:true},billing:{unit:'publication',quoteable:true}},
 {capability_id:'publish.paid_media',family:'distribution',version:'1.0.0',request_schema_ref:'opengeo-publication.v1.schema.json',result_schema_ref:'opengeo-publication.v1.schema.json',execution:{public_model:'job',turnaround_classes:['best_effort'],supports_partial_results:false,supports_cancel:true,supports_prefer_wait:false},billing:{unit:'publication',quoteable:true}},
 {capability_id:'verify.recheck',family:'verification',version:'1.0.0',request_schema_ref:'opengeo-job.v1.schema.json',result_schema_ref:'opengeo-observation.v1.schema.json',execution:{public_model:'job',turnaround_classes:['best_effort','expedited'],supports_partial_results:true,supports_cancel:true,supports_prefer_wait:true},billing:{unit:'observation',quoteable:true}},
 {capability_id:'metrics.compute',family:'verification',version:'1.0.0',request_schema_ref:'opengeo-job.v1.schema.json',result_schema_ref:'opengeo-metric-result.v1.schema.json',execution:{public_model:'job',turnaround_classes:['interactive'],supports_partial_results:false,supports_cancel:false,supports_prefer_wait:true},billing:{unit:'metric_run',quoteable:false}}
];
