export type Availability = 'observed'|'not_requested'|'not_supported'|'not_available'|'failed_to_extract'|'redacted'|'unknown';
export type TurnaroundClass = 'best_effort'|'expedited'|'interactive';
export type InteractionMode = 'standard'|'reasoning'|'search'|'reasoning_search';
export type JobStatus = 'queued'|'running'|'partial'|'succeeded'|'failed'|'cancelled'|'finalized_partial';
export type ResultState = 'none'|'partial'|'sufficient'|'complete'|'finalized_partial';
export interface CapabilityDefinition { capability_id:string; family:'discovery'|'observation'|'retrieval'|'analysis'|'generation'|'distribution'|'verification'; version:string; request_schema_ref:string; result_schema_ref:string; execution:{public_model:'job';turnaround_classes:TurnaroundClass[];supports_partial_results:boolean;supports_cancel:boolean;supports_prefer_wait?:boolean}; billing:{unit:string;quoteable?:boolean}; dimensions?:Record<string,unknown>; optional_modules?:string[]; health?:Record<string,unknown>; }
export interface JobProgress { total_items:number; completed_items:number; failed_items:number; cancelled_items:number; completion_ratio:number }
export interface Job { id:string; object:'opengeo.job'; capability_id:string; status:JobStatus; result_state:ResultState; turnaround_class:TurnaroundClass; progress?:JobProgress; requested_config?:Record<string,unknown>; effective_config?:Record<string,unknown>; billing?:{state:string;currency?:string;reserved_amount?:string|null;settled_amount?:string|null}; health?:{status:'operational'|'delayed'|'degraded'|'unavailable';estimated_completion_at?:string|null;message?:string|null}; warnings?:Array<Record<string,unknown>>; timestamps:{created_at:string;updated_at:string;started_at?:string|null;completed_at?:string|null}; links?:Record<string,string> }
export interface PromptRef { prompt_id:string; version_id:string; text:string }
export interface SourceItem { index?:number|null; url:string; canonical_url?:string|null; domain?:string|null; title?:string|null; summary?:string|null; site_name?:string|null; published_at?:string|null; icon_asset_id?:string|null; [k:string]:unknown }
export interface Collection<T=SourceItem> { availability:Availability; items:T[] }
export interface Observation { id:string; object:'opengeo.observation'; schema_version:string; job_id:string; prompt:PromptRef; target:{engine:string;surface:'web'|'mobile'|'api'|'local';interaction_mode:InteractionMode;turnaround_class:TurnaroundClass;language?:string|null;region?:string|null}; collection:{method:'managed_api'|'local_sampler'|'manual_import';profile_version:string;requested_at?:string|null;observed_at:string;repeat_index:number}; answer:{availability:Availability;format?:string|null;text?:string|null}; retrieved_sources?:Collection; explicit_citations?:Collection; brand_mentions?:BrandMention[]; rankings?:Ranking[]; recommended_questions?:Collection<Record<string,unknown>>; search_terms?:Collection<Record<string,unknown>>; videos?:Collection<Record<string,unknown>>; products?:Collection<Record<string,unknown>>; evidence?:Record<string,unknown>; quality:{is_valid:boolean;completeness_score:number;warnings:Array<Record<string,unknown>>}; provenance:{normalizer_version:string;entity_parser_version:string;ranking_parser_version:string}; extensions?:Record<string,unknown> }
export interface BrandMention { entity_id:string; entity_name:string; aliases_matched:string[]; mentioned:boolean; mention_count:number; rank?:number|null; context?:string|null; sentiment?:string|null; derivation:'provider_supplied'|'opengeo_parser'|'human_corrected' }
export interface Ranking { entity_id:string; entity_name?:string; rank:number; context?:string|null; derivation:'provider_supplied'|'opengeo_parser'|'human_corrected' }
export interface Prompt { prompt_id:string; objective_id:string; version_id:string; text:string; language?:string; intent?:string|null; topic?:string|null; source:{type:string;source_text?:string|null;parent_prompt_version_id?:string|null}; status:'draft'|'suggested'|'approved'|'archived'; approved_by?:string|null; tags?:string[]; default_sampling:{repeat_count:number;interaction_mode:InteractionMode;turnaround_class:TurnaroundClass} }
export interface Publication { id:string; object:'opengeo.publication'; channel_type:'owned_site'|'paid_media'|'social_channel'; status:'draft'|'pending_confirmation'|'queued'|'publishing'|'published'|'failed'|'submission_unknown'|'cancelled'; content_asset_id:string; target_id?:string|null; published_url?:string|null; proof_asset_id?:string|null; failure?:Record<string,unknown>|null; created_at:string; updated_at?:string|null }
export interface MetricResult { metric_id:string; metric_version:string; value:number|null; unit?:string; scope:Record<string,unknown>; sample:{planned:number;valid:number;included:number;excluded:number}; evidence_query:Record<string,unknown>; computed_at?:string }
