export interface OpenGEOClientOptions { baseUrl: string; apiKey?: string; fetch?: typeof globalThis.fetch }
export interface MonitorRunRequest { capability_id: 'observe.ai_answer'; prompts: Array<string | Record<string, unknown>>; turnaround_class?: 'best_effort' | 'expedited' | 'interactive'; interaction_mode?: 'standard' | 'reasoning' | 'search' | 'reasoning_search'; monitoring_profile?: 'cn-search-v1' | 'global-llm-v1' }
export interface FinalizePartialRequest { cancel_remaining?: boolean }
export class OpenGEOClient {
  private readonly request: typeof globalThis.fetch;
  constructor(private readonly options: OpenGEOClientOptions) { this.request = options.fetch ?? globalThis.fetch; }
  private endpoint(path: string): string { return `${this.options.baseUrl.replace(/\/$/, '')}${path}`; }
  private headers(initial: Record<string, string> = {}): Record<string, string> { return this.options.apiKey ? { ...initial, authorization: `Bearer ${this.options.apiKey}` } : initial; }
  async capabilities<T = unknown>(): Promise<T> { const r = await this.request(this.endpoint('/v1/capabilities'), { headers: this.headers() }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
  async getJob<T = unknown>(id: string): Promise<T> { const r = await this.request(this.endpoint(`/v1/jobs/${encodeURIComponent(id)}`), { headers: this.headers() }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
  async getJobItems<T = unknown>(id: string): Promise<T> { const r = await this.request(this.endpoint(`/v1/jobs/${encodeURIComponent(id)}/items`), { headers: this.headers() }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
  async finalizePartial<T = unknown>(id: string, input: FinalizePartialRequest = {}): Promise<T> { const r = await this.request(this.endpoint(`/v1/jobs/${encodeURIComponent(id)}/finalize-partial`), { method: 'POST', headers: this.headers({ 'content-type': 'application/json' }), body: JSON.stringify(input) }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
  async cancelJob<T = unknown>(id: string): Promise<T> { const r = await this.request(this.endpoint(`/v1/jobs/${encodeURIComponent(id)}/cancel`), { method: 'POST', headers: this.headers() }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
  async createMonitorRun<T = unknown>(input: MonitorRunRequest, idempotencyKey: string, preferWaitMs?: number): Promise<T> { const headers: Record<string, string> = this.headers({ 'content-type': 'application/json', 'idempotency-key': idempotencyKey }); if (preferWaitMs !== undefined) headers.prefer = `wait=${Math.max(0, Math.floor(preferWaitMs / 1000))}`; const r = await this.request(this.endpoint('/v1/monitor-runs'), { method: 'POST', headers, body: JSON.stringify(input) }); if (!r.ok) throw new Error(`OpenGEO request failed: ${r.status}`); return r.json() as Promise<T>; }
}
